### ISSUE TITLE
[Feature Request] List all gitmojis

### ISSUE THREAD

**Issue by lucasrabiec** [techouse/alfred-gitmoji#2]
Hi, is it possible to add a feature for displaying a list of all gitmojis (with descriptions) when there is no query (like in the emoji workflow)?

Current:
<img width="602" alt="CleanShot 2022-11-06 at 05 07 06@2x" src="https://user-images.githubusercontent.com/9741188/200153686-4a285d76-dd52-41d6-821e-883c4e21860e.png">

Expected:
<img width="590" alt="CleanShot 2022-11-06 at 05 09 08@2x" src="https://user-images.githubusercontent.com/9741188/200153704-2e744f93-8120-4981-be19-25072d7e401e.png">

**Comment by techouse** [comment]
Hi,

Probably yes. I'll try and add it next weekend.

**Comment by techouse** [comment]
Addressed in https://github.com/techouse/alfred-gitmoji/commit/6c1b79cd374c1af995fdf8edd240ee21b20dc24f

Released in [v1.19](https://github.com/techouse/alfred-gitmoji/releases/tag/v1.1.9)
