### ISSUE TITLE
✨ Copy actual emoji to clipboard

### ISSUE THREAD

**Issue by go-sean-go** [techouse/alfred-gitmoji#3]
Is there some way we could have an option to copy the actual emoji to the clipboard? So, ⚡️ and not `:zap:`. Perhaps this is configurable, since different users may have varying needs? (If this is already possible, my apologies! I'm new to Alfred packs.)

**Comment by techouse** [comment]
Hey,

Good idea, I'll look into it.

**Comment by techouse** [comment]
I added modifier keys in [`v1.2.0`](https://github.com/techouse/alfred-gitmoji/releases/tag/v1.2.0)

### Modifier keys

- <kbd>return</kbd> (↵): Copy the code of the selected gitmoji (e.g. `:bug:`) directly to your front-most application.
- <kbd>option+return</kbd> (⌥↵): Copy the symbol of the selected emoji) (e.g. "🐛") to your clipboard.
- <kbd>ctrl+return</kbd> (⌃↵): Copy the hexadecimal HTML Entity of the selected emoji) (e.g. `&#x1f41b;`) to your clipboard.
- <kbd>shift+return</kbd> (⇧↵): Copy the Python source of the selected emoji) (e.g. `u"\U0001F41B"`) to your clipboard.
- <kbd>shift+ctrl+return</kbd> (⇧⌃↵): Copy the formal Unicode notation of the selected emoji) (e.g. `U+1F41B`) to your clipboard.
- <kbd>cmd+return</kbd> (⌘↵): Copy the code of the selected emoji (e.g. `:bug:`) to your clipboard.
